name: editor
description: dlox editor
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_icons: ^1.1.0
  flutter_parsed_text: ^2.1.0
  provider: ^5.0.0
  url_launcher: ^6.0.2
  sprintf: ^6.0.0 # WHY?
  code_text_field: ^1.0.2
  dlox:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/snippets/
  fonts:
    - family: SourceCode
      fonts:
        - asset: assets/fonts/sourceCode/SourceCodePro-Black.ttf
          weight: 900
        - asset: assets/fonts/sourceCode/SourceCodePro-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/sourceCode/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/sourceCode/SourceCodePro-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/sourceCode/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/sourceCode/SourceCodePro-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/sourceCode/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/sourceCode/SourceCodePro-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/sourceCode/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/sourceCode/SourceCodePro-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/sourceCode/SourceCodePro-Light.ttf
          weight: 300
        - asset: assets/fonts/sourceCode/SourceCodePro-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/sourceCode/SourceCodePro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/sourceCode/SourceCodePro-ExtraLightItalic.ttf
          style: italic
          weight: 200
